### ISSUE TITLE
'checkpoints' is already used

### ISSUE THREAD

**Issue by Coxev** [ManiaControl/ManiaControl#178]
Hello, when I want to start ManiaControl, it says that :

[ManiaControl ERROR]: Field name 'checkpoints' already used
File&Line: D:\ServeurTrackmania\ManiaControl-0.226\plugins\MCTeam\LocalRecordsPlugin.php: 186
Quitting ManiaControl after Fatal Error.
Quitting ManiaControl!

But I changed nothing, I understand nothing, could you help me please ? (It's my first experience in Trackmania servers)

**Comment by casjeme** [comment]
Hello Coxev,

I experienced the same problem few minutes ago. Problem is because of SQL query in this file that add a 'chekpoints' column in all case, not only if not exists.
To fix this issue, I opened LocalRecordsPlugin.php and replaced the SQL query line 171 to 179 by :
```php
$query  = "CREATE TABLE IF NOT EXISTS `" . self::TABLE_RECORDS . "` (
				`index` int(11) NOT NULL AUTO_INCREMENT,
				`mapIndex` int(11) NOT NULL,
				`playerIndex` int(11) NOT NULL,
				`time` int(11) NOT NULL,
				`changed` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
				`checkpoints` text NOT NULL,
				PRIMARY KEY (`index`),
				UNIQUE KEY `player_map_record` (`mapIndex`,`playerIndex`)
				) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;";
```

Note : I added a line for the 'checkpoints' column after 'changed' column.

After that, I removed the second SQL query bloc (line 185 to 190) :
```php
$mysqli->query("ALTER TABLE `" . self::TABLE_RECORDS . "` ADD `checkpoints` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL");
		if ($mysqli->error) {
			if (!strstr($mysqli->error, 'Duplicate')) {
				trigger_error($mysqli->error, E_USER_ERROR);
			}
		}
```

Hope that will work fine for you.

**Comment by kremsy** [comment]
Thanks for your inputs, can you make a pull request with your changes, than I will investigate and merge it.

**Comment by kremsy** [comment]
Good that its always added but, we should leave the alter table in for cases that some database could not have them yet (with a comment to be removed in some months).

**Comment by axelalex2** [comment]
Guess it can be closed.
