### ISSUE TITLE
Negative times with LocalRecordsCPLivePlugin on RPG TitlePack

### ISSUE THREAD

**Issue by QuozPowa** [ManiaControl/ManiaControl#255]
A player pointed out me that LocalRecordsCPLivePlugin displays him negative CP times : 
[https://cdn.discordapp.com/attachments/577859289692241940/712002848472170558/tm_a.png](https://cdn.discordapp.com/attachments/577859289692241940/712002848472170558/tm_a.png)

The map can be downloaded via this link : [https://tm.mania-exchange.com/tracks/193522/rpg-crystalgia-cup-version](https://tm.mania-exchange.com/tracks/193522/rpg-crystalgia-cup-version)

**Comment by axelalex2** [comment]
Okay, this is very strange, but the LocalRecordsCPLivePlugin is made not from the MCTeam itself. Maybe there is a bug in the ManiaControl-core resulting in this behaviour, but it would make more sense, if we would hear some input from the plugin-developer @jonthekiller .

**Comment by jonthekiller** [comment]
I can't reproduce it. I tried in V0.251 and v0.254 and with this map.

![image](https://user-images.githubusercontent.com/5202324/82328832-a77e0780-99e0-11ea-8855-320421d7d175.png)

**Comment by axelalex2** [comment]
Now i'm questioning, which checkpoints are saved for this local, as this is the comparison the plugin makes. @QuozPowa Any chance you can look up the checkpoints saved for this local?

**Comment by QuozPowa** [comment]
Yes, I have two records for this map (in different versions) : 
``` 32915611393,21423,32544,47625,61084,78401,91930,101448,112658,120617,126888,138595,155058,168756,191442,201954,```

and
```20147311369,21223,32759,47757,61539,78757,92391,101699,112754,120808,127049,138909,154818,168211,190981,```

**Comment by axelalex2** [comment]
Wow, those first CP times are more than messed up. The rest of the CPs look fine, but those look more like C-style uninitialized integers. Or maybe from the first CPs `32915611393` and `20147311369` only the last 5 digits are the legit ones. Those 11s CPs would fit more to the 12s screenshot jonthekiller has sent in here.
What was the final finishing time you had on both versions? I'm taking a guess on `5:29.156` and `3:21.473`?

**Comment by axelalex2** [comment]
Actually, you don't even have to answer me, i investigated based on my suspicion, and i was correct. The local records get saved through the finish-trigger, saving all CPs and cleaning the CP-cache, then an additional CP-trigger (which should happen before the finish-trigger) gets triggered, which saves the CP time in a now empty CP-cache. The first run you do on a map is fine, the 2nd is messed up because of that.
The fix will be available in v0.255, and for your currently broken times, you can either delete the record with "//delrec <rank>", edit the checkpoints in the database itself (shutdown ManiaControl while editing), or simply drive a faster time.
