### ISSUE TITLE
Player statistics aren't paginated

### ISSUE THREAD

**Issue by Chris92de** [ManiaControl/ManiaControl#39]
Only shows Top14 players.
Pls fix =)

**Comment by kremsy** [comment]
The Player statistic widget are kinda obsolete and I wanted to remove them since long time anyway, I wanted to make at some point something great instead of this but I don't have time enough, so I hope one of the Plugin Authors will make something new at some point :).

I can take a look into it, but I can't tell you exactly when I have time for it.

**Comment by kremsy** [comment]
@JocyW  is this already fixed?
