### ISSUE TITLE
full trackmania support

### ISSUE THREAD

**Issue by kremsy** [ManiaControl/ManiaControl#57]

**Comment by kremsy** [comment]
not much todo actually, just verify everything, fully implement callbacks, update and check localrecords and dedimania

**Comment by w1lla** [comment]
Todo: 

- Implement the rest of the Callbacks, will follow hopefully for the end of this weekend.
- Verify everything.
- Re-check localrecords and maybe add new values in database plugin.
- Recheck dedimania for vital solutions but need to re-check dedicated server due to the error posted by others of packs not properly working.

Currently tested ScriptMode:
- TimeAttack.

**Comment by kremsy** [comment]
Most important to get Dedimania running, would be cool if you would have some time for it @w1lla  :).

**Comment by kremsy** [comment]
everything should have been done so far
